/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 * define: STM32F429xx
 *
 *
 */

#include <stdint.h>

#include "stm32f429xx.h"

#include "Helpers/logger.h"
#include "usbd_framework.h"

#define ever			;;


int main(void)
{
	log_info("program entrypoint");

//	usbd_initialize();

    /* Loop forever */
	for(ever)
	{

	}
}
