/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "LCD_Pins.h"
#include "ILI9341.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever	;;

int main(void)
{
	delay_init(180000000);
	LCD_Pin_Init();
	LCD_SPI_Init();
	ILI9341_Init();
	ILI9341_setRotation(2);
	ILI9341_Fill(COLOR_RED);

    /* Loop forever */
	for(;;)
	{
		ILI9341_Fill(COLOR_YELLOW);
		ILI9341_Fill(COLOR_PURPLE);
	}
}
